# Generated by Django 4.2.16 on 2025-02-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=255)),
                ('mandatory', models.BooleanField(default=False)),
                ('required_for', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('kyc_status', models.BooleanField(default=False)),
                ('role', models.IntegerField(null=True)),
                ('user', models.IntegerField(null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.address')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilMoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_social', models.CharField(max_length=255)),
                ('numero_immatriculation', models.CharField(max_length=255)),
                ('matricule_fiscale', models.CharField(max_length=255)),
                ('registre_commerce', models.CharField(max_length=255)),
                ('contact_responsable', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('forme_juridique', models.CharField(max_length=255)),
                ('secteur_activite', models.CharField(max_length=255)),
                ('logo', models.CharField(verbose_name='max_length=255')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profiles.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_url', models.URLField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.documenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.profil')),
            ],
        ),
    ]
