# Generated by Django 4.2.16 on 2025-03-05 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profilmoral',
            name='email',
        ),
        migrations.AddField(
            model_name='profilmoral',
            name='business_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilmoral',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='profilmoral',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moral_profiles', to='profiles.profil'),
        ),
        migrations.CreateModel(
            name='PhysicalProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_profiles', to='profiles.profil')),
            ],
        ),
    ]
