# Generated by Django 4.2.16 on 2025-03-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profil_date_of_birth_remove_profil_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='role',
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
