# Generated by Django 4.2.16 on 2025-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profil_role_alter_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
