# Generated by Django 4.2.16 on 2025-03-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profil_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalprofil',
            name='date_of_birth',
        ),
    ]
