# Generated by Django 4.2.16 on 2025-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profil_user_physicalprofil_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='type_profil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
