# Generated by Django 4.2.16 on 2025-06-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profil_type_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.profil')),
            ],
        ),
    ]
